# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# TCL: imports/src/Mercury_XU5_gmii2rgmii_timing.tcl

# XDC: imports/src/Mercury_XU5_LED_timing.xdc

# TCL: imports/src/Mercury_XU5_PE1.tcl

# Block Designs: bd/Mercury_XU5/Mercury_XU5.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5 || ORIG_REF_NAME==Mercury_XU5} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_zynq_ultra_ps_e_0/Mercury_XU5_zynq_ultra_ps_e_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_zynq_ultra_ps_e_0 || ORIG_REF_NAME==Mercury_XU5_zynq_ultra_ps_e_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_system_management_wiz_0/Mercury_XU5_system_management_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_system_management_wiz_0 || ORIG_REF_NAME==Mercury_XU5_system_management_wiz_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_led_0/Mercury_XU5_led_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_led_0 || ORIG_REF_NAME==Mercury_XU5_led_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_ddr4_0/Mercury_XU5_ddr4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_ddr4_0 || ORIG_REF_NAME==Mercury_XU5_ddr4_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_xbar_0/Mercury_XU5_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_xbar_0 || ORIG_REF_NAME==Mercury_XU5_xbar_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_auto_cc_0/Mercury_XU5_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_auto_cc_0 || ORIG_REF_NAME==Mercury_XU5_auto_cc_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_auto_ds_0/Mercury_XU5_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_auto_ds_0 || ORIG_REF_NAME==Mercury_XU5_auto_ds_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_auto_pc_0/Mercury_XU5_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_auto_pc_0 || ORIG_REF_NAME==Mercury_XU5_auto_pc_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_auto_rs_0/Mercury_XU5_auto_rs_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_auto_rs_0 || ORIG_REF_NAME==Mercury_XU5_auto_rs_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_auto_rs_w_0/Mercury_XU5_auto_rs_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_auto_rs_w_0 || ORIG_REF_NAME==Mercury_XU5_auto_rs_w_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_axi_interconnect_0_0/Mercury_XU5_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_axi_interconnect_0_0 || ORIG_REF_NAME==Mercury_XU5_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_clk_wiz_0_0/Mercury_XU5_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_clk_wiz_0_0 || ORIG_REF_NAME==Mercury_XU5_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_ps_sys_rst_0/Mercury_XU5_ps_sys_rst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_ps_sys_rst_0 || ORIG_REF_NAME==Mercury_XU5_ps_sys_rst_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_ddr4_sys_rst_0/Mercury_XU5_ddr4_sys_rst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_ddr4_sys_rst_0 || ORIG_REF_NAME==Mercury_XU5_ddr4_sys_rst_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_smartconnect_00_0/Mercury_XU5_smartconnect_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_smartconnect_00_0 || ORIG_REF_NAME==Mercury_XU5_smartconnect_00_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_reg_bank_0_0/Mercury_XU5_reg_bank_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mercury_XU5_reg_bank_0_0 || ORIG_REF_NAME==Mercury_XU5_reg_bank_0_0} -quiet] -quiet

# XDC: /home/wto/Eos/ME-XU5-2EG-1I-D11E/Mercury_XU5_PE1.gen/sources_1/bd/Mercury_XU5/Mercury_XU5_ooc.xdc
