# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wto/Eos/EosMuon/ME-XU5-2EG-1I-D11E/Mercury_XU5_PE1.srcs/sources_1/ip/event192_fifo/event192_fifo.xci
# IP: The module: 'event192_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wto/Eos/EosMuon/ME-XU5-2EG-1I-D11E/Mercury_XU5_PE1.gen/sources_1/ip/event192_fifo/event192_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'event192_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/wto/Eos/EosMuon/ME-XU5-2EG-1I-D11E/Mercury_XU5_PE1.gen/sources_1/ip/event192_fifo/event192_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'event192_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/wto/Eos/EosMuon/ME-XU5-2EG-1I-D11E/Mercury_XU5_PE1.srcs/sources_1/ip/event192_fifo/event192_fifo.xci
# IP: The module: 'event192_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wto/Eos/EosMuon/ME-XU5-2EG-1I-D11E/Mercury_XU5_PE1.gen/sources_1/ip/event192_fifo/event192_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'event192_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/wto/Eos/EosMuon/ME-XU5-2EG-1I-D11E/Mercury_XU5_PE1.gen/sources_1/ip/event192_fifo/event192_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'event192_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
